### PR TITLE
User Interface for the program

### LINKED ISSUE #3: Add user interface
There was talk about some simple user interface for this.

### PR DESCRIPTION
**Pull request by SKR301**
Adding UI for better visualization and control #3 

+ index.html
+ api.js (DELETE)

### CODE REVIEW

**Comment by norkator** [comment]
I tested it. Its very nice and suits this small app very well.

**Comment by norkator** [comment]
@SKR301 I left you some
`    order: [
        ['id', 'DESC'],
      ],`

samples.. I don't know what you wanted to order exactly and why.. look from /models/'model_file'.js for what fields you can use to order with.

**Review by norkator — DISMISSED** [review]
Currently approve this as is.

**Comment by SKR301** [comment]
Finalized the code...review it at your convenience...
Peace OUT!

**Review by norkator — APPROVED** [review]

**Pull request merged**
